[package]
tool = "kryon"
name = "workbook"
entry = "src/app.zi"
module_roots = ["src", "tests"]
bridge_modules = ["app"]

[toolchain]
git = "https://github.com/ziranlang/ziran.git"
ref = "master"

[dependencies.kryon]
git = "https://github.com/kryonlabs/kryon.git"
ref = "master"

[dependencies.mingcute]
git = "https://github.com/kryonlabs/mingcute.git"
ref = "master"

[dependencies.kss]
git = "https://github.com/kryonlabs/kss.git"
ref = "master"

[install]
bin = "workbook"

[tool.kryon]
default_profile = "desktop"

[tool.kryon.profiles.desktop]
backend = "desktop"

[tool.kryon.install]
profile = "desktop"
name = "Workbook"
comment = "Spreadsheet editor compatible with Gnumeric"
categories = "Office;Spreadsheet;"
